spring:
  profiles:
    default: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/schedule_db
    generate-unique-name: false
    username: postgres
    password: password

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: schedule_schema

  flyway:
    schemas:
      - schedule_schema
    default-schema: schedule_schema
    create-schemas: true

server:
  port: 8080